name: lint test and deploy

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pull code from repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: lint code
        run: npm run lint
      - name: test code with automated tests
        run: npm run test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to a server somewhere
        run: echo "Deploying..."
