name: lint test and deploy

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to a server somewhere
        run: echo "Deploying..."
